sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gdb

script:
  - echo ${COMPILER}
  - echo ${CXX}
  - $CXX --version
  - $CXX -std=c++11 -Wall -Werror -Wextra -pedantic-errors -I. test_weak_ref.cpp
  - gdb -batch -ex "run" -ex "thread apply all bt" -ex "quit" --args ./a.out
